### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by jdaviescoates** [grayleonard/booxtream-epub-drm-remover#13]
I recently purchased a book on Degrowth from Verso only to discover their silly social DRM watermarks and so ended up here because I want to remove them.

Forgive my ignorance (I don't think I've ever actually tried to install/ use a python script before), but at present cure.py doesn't seem to even install :(

```
~/Downloads$ python cure.py 
  File "cure.py", line 8
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

```

Or am I just doing something wrong?

I'd love to use this, so am hoping it's still being maintained and someone can help me? :)

thanks in advance!

**Comment by jdaviescoates** [comment]
OK, so I was being silly and hadn't download the file properly, but now I just get this:

```
/Downloads$ python cure.py 
Traceback (most recent call last):
  File "cure.py", line 29, in <module>
    from bs4 import BeautifulSoup as bs
ImportError: No module named bs4
```

But I have installed bs4

```
$ pip install bs4
Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
Requirement already satisfied: beautifulsoup4 in /home/josef/.local/lib/python3.8/site-packages (from bs4) (4.11.1)
Requirement already satisfied: soupsieve>1.2 in /home/josef/.local/lib/python3.8/site-packages (from beautifulsoup4->bs4) (2.3.2.post1)
Building wheels for collected packages: bs4
  Building wheel for bs4 (setup.py) ... done
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1272 sha256=5e364adf9add1bb374a935bca16ccbdc0f161cb618bd051d8e8ed40d412e3174
  Stored in directory: /home/josef/.cache/pip/wheels/75/78/21/68b124549c9bdc94f822c02fb9aa3578a669843f9767776bca
Successfully built bs4
Installing collected packages: bs4
Successfully installed bs4-0.0.1
```

But I guess there is some other issue

**Comment by deimidis** [comment]
Hi, i just found this script today and I make it work. Just you are still searching for a solution, what it worked for me was to create a virtual environment for python 2  (as my os use python 3) and then installed both libraries (BeatifulSoup and Wand) and it worked. I've done it on linux

**Comment by BrianZbr** [comment]
> create a virtual environment for python 2 (as my os use python 3) and then installed both libraries (BeatifulSoup and Wand)

I tried this but it's complaining about PyQt5 and I can't get that to install on Python 2.7.

**Comment by C0m3b4ck** [comment]
@BrianZbr , I have made a version for Python3 with some more (small) features. Check it out if you are having any Python2.7 problems: https://github.com/C0m3b4ck/pagewipe-epub-drm-remover

**Comment by C0m3b4ck** [comment]
@jdaviescoates  could you tell me three major things please: 1. Are you using a Virtual Environment (venv) for Python or are you not? 2. Are you using Python2.7 as your main Python version? 3. Are you on Linux or Windows?
